name: Validation JSON

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: validate
      uses: GrantBirki/json-yaml-validate@v2.3.1
      with:
        files: data/test.json
        json_schema: schemas/schema.json

  another-json:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: validate
      uses: GrantBirki/json-yaml-validate@v2.3.1
      with:
        files: data/topic.json
        json_schema: schemas/schema2.json

